apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: expense-tracker
  labels:
    app: expense-service
    service: expense
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: expense-service

