# ServiceAccount for auth-service
# Used for IRSA (IAM Roles for Service Accounts) to access AWS services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: expense-tracker
  labels:
    app: auth-service
  # Annotations for IRSA - IAM role ARN will be injected by Terraform
  annotations:
    eks.amazonaws.com/role-arn: <IRSA_ROLE_ARN>  # Will be replaced by Kustomize or Terraform

