apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: expense-tracker
  labels:
    app: notification-service
data:
  server-port: "8083"
  aws-region: "us-east-1"
  expense-events-queue-url: "<EXPENSE_EVENTS_QUEUE_URL>"
  receipt-events-queue-url: "<RECEIPT_EVENTS_QUEUE_URL>"
  auth-events-queue-url: "<AUTH_EVENTS_QUEUE_URL>"
  notification-email-topic-arn: "<NOTIFICATION_EMAIL_TOPIC_ARN>"

