apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: expense-tracker

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - configmap.yaml

commonLabels:
  app: notification-service
  service: notification

images:
  - name: <IMAGE_TAG>
    newName: <IMAGE_REPOSITORY>
    newTag: <IMAGE_TAG>

