apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: expense-tracker
  labels:
    app: notification-service
  annotations:
    eks.amazonaws.com/role-arn: <IRSA_ROLE_ARN>

